enable the country data report to plot more parameter values that hav…
HopkinsIDD/cholera-mapping-pipeline pull request #340
Opened 2023-03-23 17:48 UTC by KaiyueZou

…e been estimated

2023-03-27 04:47 UTC, eclee25 requested changes
For the trace plot functions, rather than checking if each parameter exists based on the config options, is it possible to have a more generic function that tries to plot all parameters from a pre-specified list and then skips the ones that don't exist?

2023-03-27 04:47 UTC, eclee25 commented on packages/taxdat/R/plot_MCMC.R
> +    warning("There is no time effect, meaning eta and alpha will not be shown. ")
There may still be an alpha even if the time_effect is off. We specify whether an intercept should be in the model separately

2023-03-27 04:47 UTC, eclee25 commented on packages/taxdat/R/plot_MCMC.R
> +    warning("There is no time effect, meaning eta and alpha will not be shown. ")
same comment as above

2023-03-28 15:41 UTC, KaiyueZou commented
> ove works for me. However

I see, I will change the warning message

2023-03-29 15:15 UTC, merged